// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: proto/vision.proto

package proto

import (
	visionpb "cloud.google.com/go/vision/v2/apiv1/visionpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoogleCloudVision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawReceiptText   string                      `protobuf:"bytes,1,opt,name=raw_receipt_text,json=rawReceiptText,proto3" json:"raw_receipt_text,omitempty"`
	RawReceiptBlocks []*GoogleCloudVision_Blocks `protobuf:"bytes,2,rep,name=raw_receipt_blocks,json=rawReceiptBlocks,proto3" json:"raw_receipt_blocks,omitempty"`
	LocaleLanguage   string                      `protobuf:"bytes,3,opt,name=locale_language,json=localeLanguage,proto3" json:"locale_language,omitempty"`
}

func (x *GoogleCloudVision) Reset() {
	*x = GoogleCloudVision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vision_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoogleCloudVision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudVision) ProtoMessage() {}

func (x *GoogleCloudVision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudVision.ProtoReflect.Descriptor instead.
func (*GoogleCloudVision) Descriptor() ([]byte, []int) {
	return file_proto_vision_proto_rawDescGZIP(), []int{0}
}

func (x *GoogleCloudVision) GetRawReceiptText() string {
	if x != nil {
		return x.RawReceiptText
	}
	return ""
}

func (x *GoogleCloudVision) GetRawReceiptBlocks() []*GoogleCloudVision_Blocks {
	if x != nil {
		return x.RawReceiptBlocks
	}
	return nil
}

func (x *GoogleCloudVision) GetLocaleLanguage() string {
	if x != nil {
		return x.LocaleLanguage
	}
	return ""
}

type GoogleCloudVision_Blocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawText     string             `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	BoundingBox []*visionpb.Vertex `protobuf:"bytes,2,rep,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
}

func (x *GoogleCloudVision_Blocks) Reset() {
	*x = GoogleCloudVision_Blocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vision_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoogleCloudVision_Blocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCloudVision_Blocks) ProtoMessage() {}

func (x *GoogleCloudVision_Blocks) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vision_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCloudVision_Blocks.ProtoReflect.Descriptor instead.
func (*GoogleCloudVision_Blocks) Descriptor() ([]byte, []int) {
	return file_proto_vision_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GoogleCloudVision_Blocks) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *GoogleCloudVision_Blocks) GetBoundingBox() []*visionpb.Vertex {
	if x != nil {
		return x.BoundingBox
	}
	return nil
}

var File_proto_vision_proto protoreflect.FileDescriptor

var file_proto_vision_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9d, 0x02, 0x0a, 0x11, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x61, 0x77, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x72, 0x61, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x4d, 0x0a, 0x12, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x43, 0x6c, 0x6f,
	0x75, 0x64, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52,
	0x10, 0x72, 0x61, 0x77, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x5f, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x65, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x1a, 0x66, 0x0a, 0x06, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x41, 0x0a, 0x0c, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x62, 0x6f, 0x78, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x65, 0x72, 0x74, 0x65, 0x78, 0x52, 0x0b, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42,
	0x6f, 0x78, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x79, 0x61, 0x74, 0x74, 0x61, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x72, 0x65, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_vision_proto_rawDescOnce sync.Once
	file_proto_vision_proto_rawDescData = file_proto_vision_proto_rawDesc
)

func file_proto_vision_proto_rawDescGZIP() []byte {
	file_proto_vision_proto_rawDescOnce.Do(func() {
		file_proto_vision_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vision_proto_rawDescData)
	})
	return file_proto_vision_proto_rawDescData
}

var file_proto_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_vision_proto_goTypes = []interface{}{
	(*GoogleCloudVision)(nil),        // 0: proto.GoogleCloudVision
	(*GoogleCloudVision_Blocks)(nil), // 1: proto.GoogleCloudVision.Blocks
	(*visionpb.Vertex)(nil),          // 2: google.cloud.vision.v1.Vertex
}
var file_proto_vision_proto_depIdxs = []int32{
	1, // 0: proto.GoogleCloudVision.raw_receipt_blocks:type_name -> proto.GoogleCloudVision.Blocks
	2, // 1: proto.GoogleCloudVision.Blocks.bounding_box:type_name -> google.cloud.vision.v1.Vertex
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vision_proto_init() }
func file_proto_vision_proto_init() {
	if File_proto_vision_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_vision_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoogleCloudVision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vision_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoogleCloudVision_Blocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vision_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_vision_proto_goTypes,
		DependencyIndexes: file_proto_vision_proto_depIdxs,
		MessageInfos:      file_proto_vision_proto_msgTypes,
	}.Build()
	File_proto_vision_proto = out.File
	file_proto_vision_proto_rawDesc = nil
	file_proto_vision_proto_goTypes = nil
	file_proto_vision_proto_depIdxs = nil
}
